### ISSUE TITLE
Link "Create Account" and "Sign In" Buttons to Authentication Component

### ISSUE THREAD

**Issue by dejmartins** [lawgeckobyglappy/lawgecko-frontend#46]
### Overview
Link the "Create Account" and "Sign In" buttons, beneath the "Ready for This Life Changing Adventure" text, to the appropriate authentication component.

### Task Details
- Identify the locations of the "Create Account" and "Sign In" buttons throughout the application.
- Update the UI to ensure that clicking on these buttons triggers the display of the authentication component.
- Verify that the authentication component handles both registration and login processes seamlessly.

### Assigned To
@hsuika

**Comment by hsuika** [comment]
- All locations for the "Create Account" and "Sign In" buttons identified within the app
- UI updated to ensure that clicking on these buttons triggers the display of the authentication component.
- Verification done on the authentication component to ensure it handles registration and login processes without any issues

**Comment by hsuika** [comment]
A couple of remarks about the signup form is that input elements First Name, Last Name, and User name allows spaces as input
